-- Initial editorial batch for QUIZesque.
-- This is intentionally NOT production-visible: questions are inserted in
-- `review` and the pack stays `draft`. Verify answers, links, wording, and
-- distractors before publishing with a named reviewer.
-- Run with a trusted database role after the foundation migration is applied.

begin;

insert into public.question_packs (slug, title, description, version, locale, state)
values (
    'launch-v1-review',
    'Launch Set v1',
    'Initial sourced editorial batch: general knowledge, vocabulary, and original logic riddles.',
    1,
    'en-IN',
    'draft'
)
on conflict (slug) do nothing;

with seed (
    seed_key, category_id, topic_slug, prompt, options, correct_index, explanation,
    source_url, source_grade, difficulty, skill, tags, position
) as (values
    ('gk-atmosphere', 'gk', 'gk.science',
     'Which gas makes up the largest share of Earth’s atmosphere near the surface?',
     array['Oxygen', 'Nitrogen', 'Argon', 'Carbon dioxide'], 1,
     'Nitrogen makes up about 78 percent of the atmosphere near Earth’s surface, making it the largest component by far.',
     'https://science.nasa.gov/earth/climate-change/greenhouse-gases/the-atmosphere-getting-a-handle-on-carbon-dioxide/', 'A', 'easy', 'recall', array['earth','atmosphere'], 1),
    ('gk-ocean', 'gk', 'gk.world',
     'About what fraction of Earth’s surface is covered by the global ocean?',
     array['29 percent', '51 percent', '71 percent', '89 percent'], 2,
     'NASA describes the global ocean as covering about 71 percent of Earth’s surface, which is why the planet looks blue from space.',
     'https://science.nasa.gov/earth/facts/', 'A', 'easy', 'recall', array['earth','ocean'], 2),
    ('gk-earth-year', 'gk', 'gk.science',
     'Approximately how long does Earth take to complete one orbit around the Sun?',
     array['24 hours', '30 days', '180 days', '365.25 days'], 3,
     'One trip around the Sun takes about 365.25 days; the extra quarter day is why calendars add a leap day about every four years.',
     'https://science.nasa.gov/earth/facts/', 'A', 'easy', 'recall', array['earth','orbit'], 3),
    ('gk-sunlight', 'gk', 'gk.science',
     'Roughly how long does sunlight take to travel from the Sun to Earth?',
     array['8 minutes 20 seconds', '1 minute 20 seconds', '24 minutes', '1 hour'], 0,
     'The average Sun–Earth distance means sunlight takes about eight minutes and twenty seconds to reach us.',
     'https://science.nasa.gov/mission/voyager/voyager-1/voyager-1-what-is-a-light-day/', 'A', 'easy', 'recall', array['sun','light'], 4),
    ('gk-aryabhata', 'gk', 'gk.history',
     'What was the name of India’s first satellite, launched in 1975?',
     array['Rohini', 'Aryabhata', 'Bhaskara', 'INSAT-1A'], 1,
     'Aryabhata was India’s first satellite. It was launched on 19 April 1975 by a Soviet Kosmos-3M rocket.',
     'https://www.isro.gov.in/aryabhata_1.html', 'A', 'easy', 'recall', array['india','space','history'], 5),
    ('gk-un-charter', 'gk', 'gk.history',
     'On what date did the United Nations Charter come into force?',
     array['26 June 1945', '24 October 1945', '1 January 1946', '10 December 1948'], 1,
     'The Charter was signed in June 1945 and came into force on 24 October 1945 after ratification by the required states.',
     'https://www.un.org/en/about-us/un-charter/', 'A', 'medium', 'recall', array['un','history'], 6),
    ('gk-dna', 'gk', 'gk.science',
     'Which phrase describes the familiar shape of a DNA molecule?',
     array['Single spiral', 'Double helix', 'Triple ring', 'Flat lattice'], 1,
     'DNA is described as a double helix: two linked strands wind around each other in a shape often compared with a twisted ladder.',
     'https://www.genome.gov/about-genomics/fact-sheets/Deoxyribonucleic-Acid-Fact-Sheet', 'A', 'easy', 'recall', array['biology','dna'], 7),
    ('gk-un-hq', 'gk', 'gk.world',
     'In which city is the United Nations Headquarters located?',
     array['Geneva', 'Nairobi', 'New York City', 'Vienna'], 2,
     'The United Nations Headquarters is at First Avenue and East 46th Street in New York City.',
     'https://www.un.org/en/visit/', 'A', 'easy', 'recall', array['un','geography'], 8),
    ('gk-rbi', 'gk', 'gk.world',
     'Under India’s monetary policy framework, what is the primary objective while also keeping growth in mind?',
     array['Maintaining price stability', 'Setting income tax rates', 'Managing railway fares', 'Choosing stock prices'], 0,
     'The Reserve Bank of India states that monetary policy’s primary objective is maintaining price stability while keeping growth in mind.',
     'https://rbi.org.in/scripts/PublicationsView.aspx?Id=18086', 'A', 'medium', 'recall', array['india','economics'], 9),
    ('gk-earth-tilt', 'gk', 'gk.science',
     'About how far is Earth’s rotational axis tilted relative to its orbital plane?',
     array['5.2 degrees', '12.0 degrees', '23.4 degrees', '45.0 degrees'], 2,
     'Earth’s axis is tilted about 23.4 degrees relative to its orbital plane, contributing to the seasonal pattern during its orbit.',
     'https://science.nasa.gov/earth/facts/', 'A', 'medium', 'recall', array['earth','seasons'], 10),

    ('word-benevolent', 'word', 'word.meanings',
     'A benevolent neighbour regularly helps others. What does benevolent mean?',
     array['Kind and helpful', 'Easily annoyed', 'Unusually wealthy', 'Strictly impartial'], 0,
     'Benevolent describes someone who is kind and helpful, especially through goodwill or charitable action.',
     'https://dictionary.cambridge.org/dictionary/english/benevolent', 'B', 'easy', 'vocabulary', array['definition'], 11),
    ('word-ephemeral', 'word', 'word.meanings',
     'The beauty of the sunset was ephemeral. What does ephemeral mean?',
     array['Difficult to notice', 'Lasting for a short time', 'Made of many colours', 'Seen every evening'], 1,
     'Ephemeral means lasting for only a short time, so the sentence says the sunset’s beauty did not last long.',
     'https://dictionary.cambridge.org/dictionary/english/ephemeral', 'B', 'medium', 'vocabulary', array['definition'], 12),
    ('word-meticulous', 'word', 'word.meanings',
     'A meticulous editor checks every comma and date. What does meticulous mean?',
     array['Careful about details', 'Quick to change plans', 'Fond of taking risks', 'Unwilling to explain'], 0,
     'Meticulous means very careful about details, which is why a meticulous editor checks small items as well as major facts.',
     'https://dictionary.cambridge.org/dictionary/english/meticulous', 'B', 'easy', 'vocabulary', array['definition'], 13),
    ('word-pragmatic', 'word', 'word.meanings',
     'Rather than argue about a perfect plan, Mina chose a pragmatic solution. What does pragmatic mean?',
     array['Based on practical results', 'Based on old customs', 'Intended to impress', 'Hard to understand'], 0,
     'Pragmatic describes an approach focused on practical consequences and workable solutions rather than theory alone.',
     'https://dictionary.cambridge.org/dictionary/english/pragmatic', 'B', 'medium', 'vocabulary', array['definition'], 14),
    ('word-lucid', 'word', 'word.meanings',
     'The guide gave a lucid explanation of the rules. What does lucid mean?',
     array['Clear and easy to understand', 'Very short but incomplete', 'Funny in an unexpected way', 'Written in formal language'], 0,
     'Lucid means expressed clearly and easy to understand, so the guide made the rules understandable.',
     'https://dictionary.cambridge.org/dictionary/english/lucid', 'B', 'easy', 'vocabulary', array['definition'], 15),
    ('word-resilient', 'word', 'word.meanings',
     'After several setbacks, the resilient team recovered and kept working. What does resilient mean?',
     array['Able to recover after difficulty', 'Likely to avoid all change', 'Known for working alone', 'Unable to make a choice'], 0,
     'Resilient describes the ability to recover or adapt after difficulty, pressure, or change.',
     'https://dictionary.cambridge.org/dictionary/english/resilient', 'B', 'medium', 'vocabulary', array['definition'], 16),
    ('word-obsolete', 'word', 'word.meanings',
     'The obsolete device could no longer connect to modern networks. What does obsolete mean?',
     array['No longer used or useful', 'Especially expensive', 'Made for outdoor use', 'Still being tested'], 0,
     'Obsolete means no longer used because something newer or more useful has replaced it.',
     'https://dictionary.cambridge.org/dictionary/english/obsolete', 'B', 'easy', 'vocabulary', array['definition'], 17),
    ('word-candid', 'word', 'word.meanings',
     'Ravi gave a candid answer about the mistake. What does candid mean?',
     array['Honest and direct', 'Carefully rehearsed', 'Loud and emotional', 'Uncertain and hesitant'], 0,
     'Candid means honest and direct, especially when someone speaks plainly about a difficult matter.',
     'https://dictionary.cambridge.org/dictionary/english/candid', 'B', 'easy', 'vocabulary', array['definition'], 18),
    ('word-alleviate', 'word', 'word.meanings',
     'The shade helped alleviate the heat for people waiting outside. What does alleviate mean?',
     array['Make less severe', 'Make more predictable', 'Move somewhere else', 'Explain in detail'], 0,
     'Alleviate means to make a problem, pain, or difficult condition less severe.',
     'https://dictionary.cambridge.org/dictionary/english/alleviate', 'B', 'medium', 'vocabulary', array['definition'], 19),
    ('word-ambiguous', 'word', 'word.meanings',
     'The instruction was ambiguous, so two readers understood it differently. What does ambiguous mean?',
     array['Open to more than one interpretation', 'Too long to remember', 'Clearly written for experts', 'Unrelated to the task'], 0,
     'Ambiguous means having more than one possible meaning, so readers can reasonably interpret the instruction differently.',
     'https://dictionary.cambridge.org/dictionary/english/ambiguous', 'B', 'medium', 'vocabulary', array['definition'], 20),

    ('riddle-clock-angle', 'riddle', 'riddle.logic',
     'At exactly 3:15, what is the smaller angle between the two hands of an analogue clock?',
     array['0 degrees', '7.5 degrees', '15 degrees', '30 degrees'], 1,
     'At 3:15 the minute hand is at 90 degrees, while the hour hand has moved 7.5 degrees past the 3; their difference is 7.5 degrees.',
     'https://www.mathsisfun.com/activity/clocks-angles.html', 'B', 'hard', 'reasoning', array['math','clock'], 21),
    ('riddle-average-speed', 'riddle', 'riddle.logic',
     'A cyclist travels 60 km at 30 km/h, then another 60 km at 60 km/h. What is the average speed for the whole trip?',
     array['30 km/h', '40 km/h', '45 km/h', '50 km/h'], 1,
     'The first leg takes two hours and the second takes one, so 120 km divided by three hours gives an average of 40 km/h.',
     'https://www.mathsisfun.com/puzzles/making-the-average-solution.html', 'B', 'medium', 'reasoning', array['math','rates'], 22),
    ('riddle-machines', 'riddle', 'riddle.logic',
     'Four identical machines make four badges in four minutes. At the same rate, how long do 100 machines need to make 100 badges?',
     array['1 minute', '4 minutes', '25 minutes', '100 minutes'], 1,
     'Each machine makes one badge in four minutes; running 100 machines together therefore makes 100 badges in four minutes.',
     'https://www.mathsisfun.com/measure/speed-velocity.html', 'B', 'medium', 'reasoning', array['math','rates'], 23),
    ('riddle-chimes', 'riddle', 'riddle.logic',
     'A clock takes 5 seconds to strike 6 times. If each gap is equal, how long will 12 strikes take?',
     array['10 seconds', '11 seconds', '12 seconds', '15 seconds'], 1,
     'Six strikes create five equal gaps, so each gap lasts one second; twelve strikes create eleven gaps and take eleven seconds.',
     'https://www.mathsisfun.com/activity/clocks-angles.html', 'B', 'medium', 'reasoning', array['math','intervals'], 24),
    ('riddle-digit-nine', 'riddle', 'riddle.wordplay',
     'When writing every whole number from 1 through 100, how many times does the digit 9 appear?',
     array['10', '11', '19', '20'], 3,
     'The digit appears ten times in the ones place and ten times in the tens place from 1 to 99; 99 contributes once to each count.',
     'https://www.mathsisfun.com/combinatorics/combinations-permutations.html', 'B', 'medium', 'reasoning', array['math','counting'], 25),
    ('riddle-take-apples', 'riddle', 'riddle.wordplay',
     'There are five apples on a table. You pick up two. How many apples are you holding?',
     array['Two', 'Three', 'Five', 'Seven'], 0,
     'The wording asks how many you picked up and are holding, so the answer is the two apples in your hands.',
     'https://dictionary.cambridge.org/dictionary/english/take', 'B', 'easy', 'reasoning', array['wordplay','careful-reading'], 26),
    ('riddle-all-but', 'riddle', 'riddle.wordplay',
     'A flock has 17 sheep. All but 9 wander away. How many sheep remain?',
     array['8', '9', '17', '26'], 1,
     'All but nine means every sheep except nine wandered away, so nine sheep remain with the flock.',
     'https://dictionary.cambridge.org/dictionary/english/but', 'B', 'easy', 'reasoning', array['wordplay','careful-reading'], 27),
    ('riddle-cuts', 'riddle', 'riddle.logic',
     'You make four straight cuts across a ribbon, each cut spanning its full width. What is the greatest number of pieces you can get?',
     array['4', '5', '6', '8'], 1,
     'With four separate full-width cuts along one ribbon, each cut adds one piece, giving five pieces altogether.',
     'https://www.mathsisfun.com/puzzles/', 'B', 'easy', 'reasoning', array['spatial','counting'], 28),
    ('riddle-matching-coins', 'riddle', 'riddle.logic',
     'A bag contains red and blue coins. Without looking, what is the fewest coins you must take to guarantee two of the same colour?',
     array['2', '3', '4', '5'], 1,
     'There are only two colours; after taking three coins, at least two must share a colour, whatever the first two were.',
     'https://www.mathsisfun.com/puzzles/', 'B', 'easy', 'reasoning', array['logic','pigeonhole'], 29),
    ('riddle-halfway', 'riddle', 'riddle.lateral',
     'A runner passes the person currently in second place during a race. What place is the runner in now?',
     array['First', 'Second', 'Third', 'It cannot be determined'], 1,
     'Passing the runner in second place moves you into that runner’s position; you are now second, not first.',
     'https://dictionary.cambridge.org/dictionary/english/second', 'B', 'easy', 'reasoning', array['wordplay','ordering'], 30)
)
insert into public.quiz_questions (
    id, version, category_id, topic_id, locale, prompt, options, correct_index,
    explanation, source_url, source_grade, source_checked_at, difficulty, skill,
    tags, state
)
select md5('launch-v1-review:' || seed_key)::uuid,
       1, s.category_id, t.id, 'en-IN', s.prompt, s.options, s.correct_index,
       s.explanation, s.source_url, s.source_grade::public.source_grade, date '2026-09-30',
       s.difficulty::public.question_difficulty, s.skill::public.question_skill,
       s.tags, 'review'::public.content_state
from seed s
join public.quiz_topics t on t.slug = s.topic_slug and t.category_id = s.category_id
on conflict (id, version) do nothing;

with seed (seed_key, position) as (values
    ('gk-atmosphere', 1), ('gk-ocean', 2), ('gk-earth-year', 3), ('gk-sunlight', 4),
    ('gk-aryabhata', 5), ('gk-un-charter', 6), ('gk-dna', 7), ('gk-un-hq', 8),
    ('gk-rbi', 9), ('gk-earth-tilt', 10), ('word-benevolent', 11),
    ('word-ephemeral', 12), ('word-meticulous', 13), ('word-pragmatic', 14),
    ('word-lucid', 15), ('word-resilient', 16), ('word-obsolete', 17),
    ('word-candid', 18), ('word-alleviate', 19), ('word-ambiguous', 20),
    ('riddle-clock-angle', 21), ('riddle-average-speed', 22), ('riddle-machines', 23),
    ('riddle-chimes', 24), ('riddle-digit-nine', 25), ('riddle-take-apples', 26),
    ('riddle-all-but', 27), ('riddle-cuts', 28), ('riddle-matching-coins', 29),
    ('riddle-halfway', 30)
)
insert into public.question_pack_items (pack_id, question_id, question_version, position)
select p.id, md5('launch-v1-review:' || seed.seed_key)::uuid, 1, seed.position
from public.question_packs p
cross join seed
where p.slug = 'launch-v1-review'
on conflict (pack_id, question_id, question_version) do nothing;

commit;
